export const brandsData = [
  {
    logo: "/groups/Bajaj.jpg",
    brandName: "Bajaj",
    salesDetails: {
      totalSales: "₹450 Cr",
      noOfSales: 360000,
      regions: ["India"],
      topProduct: "Bajaj Pulsar 150",
      growthRate: "15% YoY",
      quarterWise: [
        { quarter: "Q1", sales: "₹110 Cr", noOfSales: 30000 },
        { quarter: "Q2", sales: "₹120 Cr", noOfSales: 32000 },
        { quarter: "Q3", sales: "₹115 Cr", noOfSales: 31000 },
        { quarter: "Q4", sales: "₹105 Cr", noOfSales: 29000 },
      ],
      monthWise: [
        { month: "Jan", sales: "₹35 Cr", noOfSales: 10000 },
        { month: "Feb", sales: "₹40 Cr", noOfSales: 11000 },
        { month: "Mar", sales: "₹35 Cr", noOfSales: 10000 },
        { month: "Apr", sales: "₹40 Cr", noOfSales: 11000 },
        { month: "May", sales: "₹40 Cr", noOfSales: 11000 },
        { month: "Jun", sales: "₹40 Cr", noOfSales: 11000 },
        { month: "Jul", sales: "₹35 Cr", noOfSales: 10000 },
        { month: "Aug", sales: "₹40 Cr", noOfSales: 11000 },
        { month: "Sep", sales: "₹40 Cr", noOfSales: 11000 },
        { month: "Oct", sales: "₹35 Cr", noOfSales: 10000 },
        { month: "Nov", sales: "₹35 Cr", noOfSales: 10000 },
        { month: "Dec", sales: "₹35 Cr", noOfSales: 10000 },
      ],
    },
    inventoryReport: {
      totalStock: 12000,
      warehouses: ["Mumbai", "Chennai", "Delhi"],
      damagedUnits: 450,
      lastAudit: "2024-11-10",
    },
    operationalExpenses: {
      annual: "₹180 Cr",
      marketing: "₹40 Cr",
      RnD: "₹60 Cr",
      logistics: "₹80 Cr",
    },
    totalExpenses: {
      monthly: [
        { month: "Jan", expenses: "₹10 Cr" },
        { month: "Feb", expenses: "₹12 Cr" },
        { month: "Mar", expenses: "₹11 Cr" },
        { month: "Apr", expenses: "₹12 Cr" },
        { month: "May", expenses: "₹13 Cr" },
        { month: "Jun", expenses: "₹14 Cr" },
        { month: "Jul", expenses: "₹11 Cr" },
        { month: "Aug", expenses: "₹12 Cr" },
        { month: "Sep", expenses: "₹13 Cr" },
        { month: "Oct", expenses: "₹14 Cr" },
        { month: "Nov", expenses: "₹11 Cr" },
        { month: "Dec", expenses: "₹12 Cr" },
      ],
      quarterly: [
        { quarter: "Q1", expenses: "₹33 Cr" },
        { quarter: "Q2", expenses: "₹37 Cr" },
        { quarter: "Q3", expenses: "₹35 Cr" },
        { quarter: "Q4", expenses: "₹38 Cr" },
      ],
    },
    targetsAndAchieved: {
      annualTarget: "₹500 Cr",
      achieved: "₹450 Cr",
      quarterWise: [
        { quarter: "Q1", target: "₹125 Cr", achieved: "₹110 Cr" },
        { quarter: "Q2", target: "₹125 Cr", achieved: "₹120 Cr" },
        { quarter: "Q3", target: "₹125 Cr", achieved: "₹115 Cr" },
        { quarter: "Q4", target: "₹125 Cr", achieved: "₹105 Cr" },
      ],
      monthWise: [
        { month: "Jan", target: "₹40 Cr", achieved: "₹35 Cr" },
        { month: "Feb", target: "₹40 Cr", achieved: "₹40 Cr" },
        { month: "Mar", target: "₹40 Cr", achieved: "₹35 Cr" },
        { month: "Apr", target: "₹40 Cr", achieved: "₹40 Cr" },
        { month: "May", target: "₹40 Cr", achieved: "₹40 Cr" },
        { month: "Jun", target: "₹40 Cr", achieved: "₹40 Cr" },
        { month: "Jul", target: "₹40 Cr", achieved: "₹35 Cr" },
        { month: "Aug", target: "₹40 Cr", achieved: "₹40 Cr" },
        { month: "Sep", target: "₹40 Cr", achieved: "₹40 Cr" },
        { month: "Oct", target: "₹40 Cr", achieved: "₹35 Cr" },
        { month: "Nov", target: "₹40 Cr", achieved: "₹35 Cr" },
        { month: "Dec", target: "₹40 Cr", achieved: "₹35 Cr" },
      ],
    },
    headOfBrand: "Rajesh Sharma",
  },
  {
    logo: "/groups/Triumph.png",
    brandName: "Triumph",
    salesDetails: {
      totalSales: "₹300 Cr",
      noOfSales: 240000,
      regions: ["India"],
      topProduct: "Triumph Bonneville",
      growthRate: "10% YoY",
      quarterWise: [
        { quarter: "Q1", sales: "₹85 Cr", noOfSales: 25000 },
        { quarter: "Q2", sales: "₹75 Cr", noOfSales: 22000 },
        { quarter: "Q3", sales: "₹70 Cr", noOfSales: 21000 },
        { quarter: "Q4", sales: "₹70 Cr", noOfSales: 21000 },
      ],
      monthWise: [
        { month: "Jan", sales: "₹30 Cr", noOfSales: 9000 },
        { month: "Feb", sales: "₹25 Cr", noOfSales: 7500 },
        { month: "Mar", sales: "₹30 Cr", noOfSales: 9000 },
        { month: "Apr", sales: "₹25 Cr", noOfSales: 7500 },
        { month: "May", sales: "₹25 Cr", noOfSales: 7500 },
        { month: "Jun", sales: "₹25 Cr", noOfSales: 7500 },
        { month: "Jul", sales: "₹20 Cr", noOfSales: 6000 },
        { month: "Aug", sales: "₹25 Cr", noOfSales: 7500 },
        { month: "Sep", sales: "₹25 Cr", noOfSales: 7500 },
        { month: "Oct", sales: "₹20 Cr", noOfSales: 6000 },
        { month: "Nov", sales: "₹25 Cr", noOfSales: 7500 },
        { month: "Dec", sales: "₹25 Cr", noOfSales: 7500 },
      ],
    },
    inventoryReport: {
      totalStock: 8000,
      warehouses: ["London", "Pune", "Hyderabad"],
      damagedUnits: 200,
      lastAudit: "2024-12-01",
    },
    operationalExpenses: {
      annual: "₹130 Cr",
      marketing: "₹30 Cr",
      RnD: "₹40 Cr",
      logistics: "₹60 Cr",
    },
    totalExpenses: {
      monthly: [
        { month: "Jan", expenses: "₹8 Cr" },
        { month: "Feb", expenses: "₹9 Cr" },
        { month: "Mar", expenses: "₹8 Cr" },
        { month: "Apr", expenses: "₹9 Cr" },
        { month: "May", expenses: "₹10 Cr" },
        { month: "Jun", expenses: "₹11 Cr" },
        { month: "Jul", expenses: "8 Cr" },
        { month: "Aug", expenses: "9 Cr" },
        { month: "Sep", expenses: "10 Cr" },
        { month: "Oct", expenses: "11 Cr" },
        { month: "Nov", expenses: "8 Cr" },
        { month: "Dec", expenses: "9 Cr" },
      ],
      quarterly: [
        { quarter: "Q1", expenses: "25 Cr" },
        { quarter: "Q2", expenses: "30 Cr" },
        { quarter: "Q3", expenses: "27 Cr" },
        { quarter: "Q4", expenses: "28 Cr" },
      ],
    },
    targetsAndAchieved: {
      annualTarget: "₹350 Cr",
      achieved: "₹300 Cr",
      quarterWise: [
        { quarter: "Q1", target: "₹90 Cr", achieved: "₹85 Cr" },
        { quarter: "Q2", target: "₹90 Cr", achieved: "₹75 Cr" },
        { quarter: "Q3", target: "₹85 Cr", achieved: "₹70 Cr" },
        { quarter: "Q4", target: "₹85 Cr", achieved: "₹70 Cr" },
      ],
      monthWise: [
        { month: "Jan", target: "₹30 Cr", achieved: "₹30 Cr" },
        { month: "Feb", target: "₹30 Cr", achieved: "₹25 Cr" },
        { month: "Mar", target: "₹30 Cr", achieved: "₹30 Cr" },
        { month: "Apr", target: "₹30 Cr", achieved: "₹25 Cr" },
        { month: "May", target: "₹30 Cr", achieved: "₹25 Cr" },
        { month: "Jun", target: "₹30 Cr", achieved: "₹25 Cr" },
        { month: "Jul", target: "₹30 Cr", achieved: "₹20 Cr" },
        { month: "Aug", target: "₹30 Cr", achieved: "₹25 Cr" },
        { month: "Sep", target: "₹30 Cr", achieved: "₹25 Cr" },
        { month: "Oct", target: "₹30 Cr", achieved: "₹20 Cr" },
        { month: "Nov", target: "₹30 Cr", achieved: "₹25 Cr" },
        { month: "Dec", target: "₹30 Cr", achieved: "₹25 Cr" },
      ],
    },
    headOfBrand: "Samantha Williams",
  },
  {
    logo: "/groups/Vespa.webp",
    brandName: "Vespa",
    salesDetails: {
      totalSales: "₹210 Cr",
      noOfSales: 126000,
      quarterWise: [
        { quarter: "Q1", sales: "₹50 Cr", noOfSales: 15000 },
        { quarter: "Q2", sales: "₹60 Cr", noOfSales: 18000 },
        { quarter: "Q3", sales: "₹45 Cr", noOfSales: 13500 },
        { quarter: "Q4", sales: "₹55 Cr", noOfSales: 16500 },
      ],
      monthWise: [
        { month: "Jan", sales: "₹15 Cr", noOfSales: 4500 },
        { month: "Feb", sales: "₹20 Cr", noOfSales: 6000 },
        { month: "Mar", sales: "₹15 Cr", noOfSales: 4500 },
        { month: "Apr", sales: "₹20 Cr", noOfSales: 6000 },
        { month: "May", sales: "₹20 Cr", noOfSales: 6000 },
        { month: "Jun", sales: "₹20 Cr", noOfSales: 6000 },
        { month: "Jul", sales: "₹15 Cr", noOfSales: 4500 },
        { month: "Aug", sales: "₹20 Cr", noOfSales: 6000 },
        { month: "Sep", sales: "₹20 Cr", noOfSales: 6000 },
        { month: "Oct", sales: "₹15 Cr", noOfSales: 4500 },
        { month: "Nov", sales: "₹20 Cr", noOfSales: 6000 },
        { month: "Dec", sales: "₹20 Cr", noOfSales: 6000 },
      ],
    },
    inventoryReport: {
      totalStock: 6000,
      warehouses: ["Jaipur", "Bangalore", "Noida"],
      damagedUnits: 120,
      lastAudit: "2024-10-25",
    },
    operationalExpenses: {
      annual: "₹80 Cr",
      marketing: "₹25 Cr",
      RnD: "₹25 Cr",
      logistics: "₹30 Cr",
    },
    totalExpenses: {
      monthly: [
        { month: "Jan", expenses: "₹5 Cr" },
        { month: "Feb", expenses: "₹6 Cr" },
        { month: "Mar", expenses: "₹5 Cr" },
        { month: "Apr", expenses: "₹6 Cr" },
        { month: "May", expenses: "₹7 Cr" },
        { month: "Jun", expenses: "₹8 Cr" },
        { month: "Jul", expenses: "5 Cr" },
        { month: "Aug", expenses: "6 Cr" },
        { month: "Sep", expenses: "7 Cr" },
        { month: "Oct", expenses: "8 Cr" },
        { month: "Nov", expenses: "5 Cr" },
        { month: "Dec", expenses: "6 Cr" },
      ],
      quarterly: [
        { quarter: "Q1", expenses: "16 Cr" },
        { quarter: "Q2", expenses: "19 Cr" },
        { quarter: "Q3", expenses: "17 Cr" },
        { quarter: "Q4", expenses: "18 Cr" },
      ],
    },
    targetsAndAchieved: {
      annualTarget: "₹250 Cr",
      achieved: "₹200 Cr",
      quarterWise: [
        { quarter: "Q1", target: "₹65 Cr", achieved: "₹55 Cr" },
        { quarter: "Q2", target: "₹65 Cr", achieved: "₹50 Cr" },
        { quarter: "Q3", target: "₹60 Cr", achieved: "₹45 Cr" },
        { quarter: "Q4", target: "₹60 Cr", achieved: "₹50 Cr" },
      ],
      monthWise: [
        { month: "Jan", target: "₹20 Cr", achieved: "₹15 Cr" },
        { month: "Feb", target: "₹20 Cr", achieved: "₹20 Cr" },
        { month: "Mar", target: "₹20 Cr", achieved: "₹15 Cr" },
        { month: "Apr", target: "₹20 Cr", achieved: "₹20 Cr" },
        { month: "May", target: "₹20 Cr", achieved: "₹20 Cr" },
        { month: "Jun", target: "₹20 Cr", achieved: "₹20 Cr" },
        { month: "Jul", target: "₹20 Cr", achieved: "₹15 Cr" },
        { month: "Aug", target: "₹20 Cr", achieved: "₹20 Cr" },
        { month: "Sep", target: "₹20 Cr", achieved: "₹20 Cr" },
        { month: "Oct", target: "₹20 Cr", achieved: "₹15 Cr" },
        { month: "Nov", target: "₹20 Cr", achieved: "₹20 Cr" },
        { month: "Dec", target: "₹20 Cr", achieved: "₹20 Cr" },
      ],
    },
    headOfBrand: "Giovanni Rossi",
  },
  {
    logo: "/groups/Tata.png",
    brandName: "Tata",
    salesDetails: {
      totalSales: "₹500 Cr",
      noOfSales: 500000,
      regions: ["India"],
      topProduct: "Tata Nexon",
      growthRate: "20% YoY",
      quarterWise: [
        { quarter: "Q1", sales: "₹115 Cr", noOfSales: 35000 },
        { quarter: "Q2", sales: "₹125 Cr", noOfSales: 38000 },
        { quarter: "Q3", sales: "₹155 Cr", noOfSales: 47000 },
        { quarter: "Q4", sales: "₹105 Cr", noOfSales: 32000 },
      ],
      monthWise: [
        { month: "Jan", sales: "₹40 Cr", noOfSales: 12000 },
        { month: "Feb", sales: "₹35 Cr", noOfSales: 10500 },
        { month: "Mar", sales: "₹40 Cr", noOfSales: 12000 },
        { month: "Apr", sales: "₹40 Cr", noOfSales: 12000 },
        { month: "May", sales: "₹40 Cr", noOfSales: 12000 },
        { month: "Jun", sales: "₹45 Cr", noOfSales: 13500 },
        { month: "Jul", sales: "₹50 Cr", noOfSales: 15000 },
        { month: "Aug", sales: "₹50 Cr", noOfSales: 15000 },
        { month: "Sep", sales: "₹55 Cr", noOfSales: 16500 },
        { month: "Oct", sales: "₹35 Cr", noOfSales: 10500 },
        { month: "Nov", sales: "₹35 Cr", noOfSales: 10500 },
        { month: "Dec", sales: "₹35 Cr", noOfSales: 10500 },
      ],
    },
    inventoryReport: {
      totalStock: 25000,
      warehouses: ["Mumbai", "Hyderabad", "Dubai"],
      damagedUnits: 500,
      lastAudit: "2024-12-15",
    },
    operationalExpenses: {
      annual: "₹600 Cr",
      marketing: "₹150 Cr",
      RnD: "₹200 Cr",
      logistics: "₹250 Cr",
    },
    totalExpenses: {
      monthly: [
        { month: "Jan", expenses: "₹20 Cr" },
        { month: "Feb", expenses: "₹22 Cr" },
        { month: "Mar", expenses: "₹21 Cr" },
        { month: "Apr", expenses: "₹22 Cr" },
        { month: "May", expenses: "₹23 Cr" },
        { month: "Jun", expenses: "₹24 Cr" },
        { month: "Jul", expenses: "₹21 Cr" },
        { month: "Aug", expenses: "₹22 Cr" },
        { month: "Sep", expenses: "₹23 Cr" },
        { month: "Oct", expenses: "₹24 Cr" },
        { month: "Nov", expenses: "₹21 Cr" },
        { month: "Dec", expenses: "₹22 Cr" },
      ],
      quarterly: [
        { quarter: "Q1", expenses: "63 Cr" },
        { quarter: "Q2", expenses: "69 Cr" },
        { quarter: "Q3", expenses: "65 Cr" },
        { quarter: "Q4", expenses: "68 Cr" },
      ],
    },
    targetsAndAchieved: {
      annualTarget: "₹1600 Cr",
      achieved: "₹1500 Cr",
      quarterWise: [
        { quarter: "Q1", target: "₹400 Cr", achieved: "₹380 Cr" },
        { quarter: "Q2", target: "₹400 Cr", achieved: "₹370 Cr" },
        { quarter: "Q3", target: "₹400 Cr", achieved: "₹380 Cr" },
        { quarter: "Q4", target: "₹400 Cr", achieved: "₹370 Cr" },
      ],
      monthWise: [
        { month: "Jan", target: "₹50 Cr", achieved: "₹40 Cr" },
        { month: "Feb", target: "₹50 Cr", achieved: "₹35 Cr" },
        { month: "Mar", target: "₹50 Cr", achieved: "₹40 Cr" },
        { month: "Apr", target: "₹50 Cr", achieved: "₹40 Cr" },
        { month: "May", target: "₹50 Cr", achieved: "₹40 Cr" },
        { month: "Jun", target: "₹50 Cr", achieved: "₹45 Cr" },
        { month: "Jul", target: "₹50 Cr", achieved: "₹50 Cr" },
        { month: "Aug", target: "₹50 Cr", achieved: "₹50 Cr" },
        { month: "Sep", target: "₹50 Cr", achieved: "₹55 Cr" },
        { month: "Oct", target: "₹50 Cr", achieved: "₹35 Cr" },
        { month: "Nov", target: "₹50 Cr", achieved: "₹35 Cr" },
        { month: "Dec", target: "₹50 Cr", achieved: "₹35 Cr" },
      ],
    },
    headOfBrand: "Ratan Kumar",
  },
];

export const mockLocations = [
  {
    brandName: "Bajaj",
    logo: "/groups/Bajaj.jpg",
    locations: [
      {
        locationName: "Pune, India",
        serviceDivisions: ["Bike", "Auto", "Commercial"],
        salesDetails: {
          totalSales: "1.2L",
          noOfSales: 36000,
          topProduct: "Bajaj Pulsar 150",
          growthRate: "15% YoY",
          quarterWise: [
            { quarter: "Q1", sales: "30K", noOfSales: 9000 },
            { quarter: "Q2", sales: "40K", noOfSales: 12000 },
            { quarter: "Q3", sales: "25K", noOfSales: 7500 },
            { quarter: "Q4", sales: "25K", noOfSales: 7500 },
          ],
        },
        storeVisits: 688,
        inventoryReport: {
          totalStock: 3000,
          damagedUnits: 100,
          lastAudit: "2024-11-10",
        },
        operationalExpenses: {
          annual: "2L",
          marketing: "50K",
          RnD: "70K",
          logistics: "80K",
        },
        totalExpenses: {
          monthly: [
            { month: "Jan", expenses: "10K" },
            { month: "Feb", expenses: "15K" },
            { month: "Mar", expenses: "12K" },
            { month: "Apr", expenses: "13K" },
            { month: "May", expenses: "14K" },
            { month: "Jun", expenses: "15K" },
            { month: "Jul", expenses: "12K" },
            { month: "Aug", expenses: "13K" },
            { month: "Sep", expenses: "14K" },
            { month: "Oct", expenses: "15K" },
            { month: "Nov", expenses: "12K" },
            { month: "Dec", expenses: "13K" },
          ],
          quarterly: [
            { quarter: "Q1", expenses: "37K" },
            { quarter: "Q2", expenses: "42K" },
            { quarter: "Q3", expenses: "39K" },
            { quarter: "Q4", expenses: "40K" },
          ],
        },
        targetsAndAchieved: {
          annualTarget: "1.5L",
          achieved: "1.4L",
          quarterWise: [
            { quarter: "Q1", target: "40K", achieved: "30K" },
            { quarter: "Q2", target: "40K", achieved: "40K" },
            { quarter: "Q3", target: "40K", achieved: "35K" },
            { quarter: "Q4", target: "30K", achieved: "35K" },
          ],
        },
        headOfBrand: "Rajiv Bajaj",
      },
      {
        locationName: "Delhi, India",
        serviceDivisions: ["Bike", "Auto"],
        salesDetails: {
          totalSales: "1L",
          noOfSales: 30000,
          topProduct: "Bajaj Pulsar 150",
          growthRate: "10% YoY",
          quarterWise: [
            { quarter: "Q1", sales: "25K", noOfSales: 7500 },
            { quarter: "Q2", sales: "25K", noOfSales: 7500 },
            { quarter: "Q3", sales: "25K", noOfSales: 7500 },
            { quarter: "Q4", sales: "25K", noOfSales: 7500 },
          ],
        },
        storeVisits: 500,
        inventoryReport: {
          totalStock: 2000,
          damagedUnits: 50,
          lastAudit: "2024-10-01",
        },
        operationalExpenses: {
          annual: "1.5L",
          marketing: "30K",
          RnD: "50K",
          logistics: "70K",
        },
        totalExpenses: {
          monthly: [
            { month: "Jan", expenses: "8K" },
            { month: "Feb", expenses: "10K" },
            { month: "Mar", expenses: "9K" },
            { month: "Apr", expenses: "10K" },
            { month: "May", expenses: "11K" },
            { month: "Jun", expenses: "12K" },
            { month: "Jul", expenses: "9K" },
            { month: "Aug", expenses: "10K" },
            { month: "Sep", expenses: "11K" },
            { month: "Oct", expenses: "12K" },
            { month: "Nov", expenses: "9K" },
            { month: "Dec", expenses: "10K" },
          ],
          quarterly: [
            { quarter: "Q1", expenses: "27K" },
            { quarter: "Q2", expenses: "33K" },
            { quarter: "Q3", expenses: "30K" },
            { quarter: "Q4", expenses: "31K" },
          ],
        },
        targetsAndAchieved: {
          annualTarget: "1.2L",
          achieved: "1L",
          quarterWise: [
            { quarter: "Q1", target: "30K", achieved: "25K" },
            { quarter: "Q2", target: "30K", achieved: "25K" },
            { quarter: "Q3", target: "30K", achieved: "25K" },
            { quarter: "Q4", target: "30K", achieved: "25K" },
          ],
        },
        headOfBrand: "Sunil Sharma",
      },
    ],
  },
  {
    brandName: "Triumph",
    logo: "/groups/Triumph.png",
    locations: [
      {
        locationName: "Bengaluru, India",
        serviceDivisions: ["Bike"],
        salesDetails: {
          totalSales: "90K",
          noOfSales: 27000,
          topProduct: "Triumph Bonneville",
          growthRate: "12% YoY",
          quarterWise: [
            { quarter: "Q1", sales: "20K", noOfSales: 6000 },
            { quarter: "Q2", sales: "25K", noOfSales: 7500 },
            { quarter: "Q3", sales: "20K", noOfSales: 6000 },
            { quarter: "Q4", sales: "25K", noOfSales: 7500 },
          ],
        },
        storeVisits: 323,
        inventoryReport: {
          totalStock: 1500,
          damagedUnits: 30,
          lastAudit: "2024-09-15",
        },
        operationalExpenses: {
          annual: "1.2L",
          marketing: "20K",
          RnD: "40K",
          logistics: "60K",
        },
        totalExpenses: {
          monthly: [
            { month: "Jan", expenses: "7K" },
            { month: "Feb", expenses: "8K" },
            { month: "Mar", expenses: "7K" },
            { month: "Apr", expenses: "8K" },
            { month: "May", expenses: "9K" },
            { month: "Jun", expenses: "10K" },
            { month: "Jul", expenses: "7K" },
            { month: "Aug", expenses: "8K" },
            { month: "Sep", expenses: "9K" },
            { month: "Oct", expenses: "10K" },
            { month: "Nov", expenses: "7K" },
            { month: "Dec", expenses: "8K" },
          ],
          quarterly: [
            { quarter: "Q1", expenses: "22K" },
            { quarter: "Q2", expenses: "27K" },
            { quarter: "Q3", expenses: "24K" },
            { quarter: "Q4", expenses: "25K" },
          ],
        },
        targetsAndAchieved: {
          annualTarget: "1L",
          achieved: "95K",
          quarterWise: [
            { quarter: "Q1", target: "25K", achieved: "20K" },
            { quarter: "Q2", target: "25K", achieved: "25K" },
            { quarter: "Q3", target: "25K", achieved: "25K" },
            { quarter: "Q4", target: "25K", achieved: "25K" },
          ],
        },
        headOfBrand: "Muthyam Swamy",
      },
      {
        locationName: "Kochi, India",
        serviceDivisions: ["Bike"],
        salesDetails: {
          totalSales: "1.1L",
          noOfSales: 33000,
          topProduct: "Triumph Bonneville",
          growthRate: "15% YoY",
          quarterWise: [
            { quarter: "Q1", sales: "30K", noOfSales: 9000 },
            { quarter: "Q2", sales: "30K", noOfSales: 9000 },
            { quarter: "Q3", sales: "25K", noOfSales: 7500 },
            { quarter: "Q4", sales: "25K", noOfSales: 7500 },
          ],
        },
        storeVisits: 412,
        inventoryReport: {
          totalStock: 1800,
          damagedUnits: 40,
          lastAudit: "2024-08-20",
        },
        operationalExpenses: {
          annual: "1.3L",
          marketing: "25K",
          RnD: "45K",
          logistics: "70K",
        },
        totalExpenses: {
          monthly: [
            { month: "Jan", expenses: "9K" },
            { month: "Feb", expenses: "10K" },
            { month: "Mar", expenses: "9K" },
            { month: "Apr", expenses: "10K" },
            { month: "May", expenses: "11K" },
            { month: "Jun", expenses: "12K" },
            { month: "Jul", expenses: "9K" },
            { month: "Aug", expenses: "10K" },
            { month: "Sep", expenses: "11K" },
            { month: "Oct", expenses: "12K" },
            { month: "Nov", expenses: "9K" },
            { month: "Dec", expenses: "10K" },
          ],
          quarterly: [
            { quarter: "Q1", expenses: "28K" },
            { quarter: "Q2", expenses: "33K" },
            { quarter: "Q3", expenses: "30K" },
            { quarter: "Q4", expenses: "31K" },
          ],
        },
        targetsAndAchieved: {
          annualTarget: "1.25L",
          achieved: "1.15L",
          quarterWise: [
            { quarter: "Q1", target: "30K", achieved: "30K" },
            { quarter: "Q2", target: "30K", achieved: "30K" },
            { quarter: "Q3", target: "30K", achieved: "25K" },
            { quarter: "Q4", target: "35K", achieved: "30K" },
          ],
        },
        headOfBrand: "Sreeshanth",
      },
    ],
  },
  {
    brandName: "Vespa",
    logo: "/groups/Vespa.webp",
    locations: [
      {
        locationName: "Hyderabad, India",
        serviceDivisions: ["Scooter"],
        salesDetails: {
          totalSales: "80K",
          noOfSales: 24000,
          topProduct: "Vespa LX 125",
          growthRate: "10% YoY",
          quarterWise: [
            { quarter: "Q1", sales: "20K", noOfSales: 6000 },
            { quarter: "Q2", sales: "20K", noOfSales: 6000 },
            { quarter: "Q3", sales: "20K", noOfSales: 6000 },
            { quarter: "Q4", sales: "20K", noOfSales: 6000 },
          ],
        },
        storeVisits: 250,
        inventoryReport: {
          totalStock: 1200,
          damagedUnits: 20,
          lastAudit: "2024-07-10",
        },
        operationalExpenses: {
          annual: "1L",
          marketing: "15K",
          RnD: "25K",
          logistics: "60K",
        },
        totalExpenses: {
          monthly: [
            { month: "Jan", expenses: "6K" },
            { month: "Feb", expenses: "7K" },
            { month: "Mar", expenses: "6K" },
            { month: "Apr", expenses: "7K" },
            { month: "May", expenses: "8K" },
            { month: "Jun", expenses: "9K" },
            { month: "Jul", expenses: "6K" },
            { month: "Aug", expenses: "7K" },
            { month: "Sep", expenses: "8K" },
            { month: "Oct", expenses: "9K" },
            { month: "Nov", expenses: "6K" },
            { month: "Dec", expenses: "7K" },
          ],
          quarterly: [
            { quarter: "Q1", expenses: "19K" },
            { quarter: "Q2", expenses: "23K" },
            { quarter: "Q3", expenses: "20K" },
            { quarter: "Q4", expenses: "21K" },
          ],
        },
        targetsAndAchieved: {
          annualTarget: "90K",
          achieved: "85K",
          quarterWise: [
            { quarter: "Q1", target: "25K", achieved: "20K" },
            { quarter: "Q2", target: "25K", achieved: "20K" },
            { quarter: "Q3", target: "20K", achieved: "20K" },
            { quarter: "Q4", target: "20K", achieved: "25K" },
          ],
        },
        headOfBrand: "Luigi Rossi",
      },
      {
        locationName: "Mumbai, India",
        serviceDivisions: ["Scooter"],
        salesDetails: {
          totalSales: "95K",
          noOfSales: 28500,
          topProduct: "Vespa LX 125",
          growthRate: "12% YoY",
          quarterWise: [
            { quarter: "Q1", sales: "25K", noOfSales: 7500 },
            { quarter: "Q2", sales: "25K", noOfSales: 7500 },
            { quarter: "Q3", sales: "20K", noOfSales: 6000 },
            { quarter: "Q4", sales: "25K", noOfSales: 7500 },
          ],
        },
        storeVisits: 309,
        inventoryReport: {
          totalStock: 1300,
          damagedUnits: 30,
          lastAudit: "2024-06-05",
        },
        operationalExpenses: {
          annual: "1.1L",
          marketing: "20K",
          RnD: "30K",
          logistics: "60K",
        },
        totalExpenses: {
          monthly: [
            { month: "Jan", expenses: "7K" },
            { month: "Feb", expenses: "8K" },
            { month: "Mar", expenses: "7K" },
            { month: "Apr", expenses: "8K" },
            { month: "May", expenses: "9K" },
            { month: "Jun", expenses: "10K" },
            { month: "Jul", expenses: "7K" },
            { month: "Aug", expenses: "8K" },
            { month: "Sep", expenses: "9K" },
            { month: "Oct", expenses: "10K" },
            { month: "Nov", expenses: "7K" },
            { month: "Dec", expenses: "8K" },
          ],
          quarterly: [
            { quarter: "Q1", expenses: "22K" },
            { quarter: "Q2", expenses: "27K" },
            { quarter: "Q3", expenses: "24K" },
            { quarter: "Q4", expenses: "25K" },
          ],
        },
        targetsAndAchieved: {
          annualTarget: "1L",
          achieved: "92K",
          quarterWise: [
            { quarter: "Q1", target: "25K", achieved: "25K" },
            { quarter: "Q2", target: "25K", achieved: "25K" },
            { quarter: "Q3", target: "25K", achieved: "20K" },
            { quarter: "Q4", target: "25K", achieved: "22K" },
          ],
        },
        headOfBrand: "Aarti Desai",
      },
    ],
  },
  {
    brandName: "Tata",
    logo: "/groups/Tata.png",
    locations: [
      {
        locationName: "Mumbai, India",
        serviceDivisions: ["Passenger", "Commercial"],
        salesDetails: {
          totalSales: "2L",
          noOfSales: 60000,
          topProduct: "Tata Nexon",
          growthRate: "18% YoY",
          quarterWise: [
            { quarter: "Q1", sales: "50K", noOfSales: 15000 },
            { quarter: "Q2", sales: "50K", noOfSales: 15000 },
            { quarter: "Q3", sales: "50K", noOfSales: 15000 },
            { quarter: "Q4", sales: "50K", noOfSales: 15000 },
          ],
        },
        storeVisits: 398,
        inventoryReport: {
          totalStock: 5000,
          damagedUnits: 100,
          lastAudit: "2024-05-20",
        },
        operationalExpenses: {
          annual: "3L",
          marketing: "50K",
          RnD: "100K",
          logistics: "150K",
        },
        totalExpenses: {
          monthly: [
            { month: "Jan", expenses: "15K" },
            { month: "Feb", expenses: "18K" },
            { month: "Mar", expenses: "16K" },
            { month: "Apr", expenses: "17K" },
            { month: "May", expenses: "18K" },
            { month: "Jun", expenses: "19K" },
            { month: "Jul", expenses: "16K" },
            { month: "Aug", expenses: "17K" },
            { month: "Sep", expenses: "18K" },
            { month: "Oct", expenses: "19K" },
            { month: "Nov", expenses: "16K" },
            { month: "Dec", expenses: "17K" },
          ],
          quarterly: [
            { quarter: "Q1", expenses: "49K" },
            { quarter: "Q2", expenses: "54K" },
            { quarter: "Q3", expenses: "51K" },
            { quarter: "Q4", expenses: "52K" },
          ],
        },
        targetsAndAchieved: {
          annualTarget: "2.5L",
          achieved: "2.3L",
          quarterWise: [
            { quarter: "Q1", target: "60K", achieved: "50K" },
            { quarter: "Q2", target: "60K", achieved: "50K" },
            { quarter: "Q3", target: "60K", achieved: "50K" },
            { quarter: "Q4", target: "70K", achieved: "60K" },
          ],
        },
        headOfBrand: "Natarajan Chandrasekaran",
      },
      {
        locationName: "Bangalore, India",
        serviceDivisions: ["Electric", "Commercial"],
        salesDetails: {
          totalSales: "1.8L",
          noOfSales: 54000,
          topProduct: "Tata Nexon EV",
          growthRate: "20% YoY",
          quarterWise: [
            { quarter: "Q1", sales: "45K", noOfSales: 13500 },
            { quarter: "Q2", sales: "45K", noOfSales: 13500 },
            { quarter: "Q3", sales: "45K", noOfSales: 13500 },
            { quarter: "Q4", sales: "45K", noOfSales: 13500 },
          ],
        },
        storeVisits: 425,
        inventoryReport: {
          totalStock: 4500,
          warehouses: ["Bangalore", "Hyderabad"],
          damagedUnits: 80,
          lastAudit: "2024-04-15",
        },
        operationalExpenses: {
          annual: "2.8L",
          marketing: "40K",
          RnD: "90K",
          logistics: "150K",
        },
        totalExpenses: {
          monthly: [
            { month: "Jan", expenses: "14K" },
            { month: "Feb", expenses: "16K" },
            { month: "Mar", expenses: "15K" },
            { month: "Apr", expenses: "16K" },
            { month: "May", expenses: "17K" },
            { month: "Jun", expenses: "18K" },
            { month: "Jul", expenses: "15K" },
            { month: "Aug", expenses: "16K" },
            { month: "Sep", expenses: "17K" },
            { month: "Oct", expenses: "18K" },
            { month: "Nov", expenses: "15K" },
            { month: "Dec", expenses: "16K" },
          ],
          quarterly: [
            { quarter: "Q1", expenses: "45K" },
            { quarter: "Q2", expenses: "50K" },
            { quarter: "Q3", expenses: "47K" },
            { quarter: "Q4", expenses: "48K" },
          ],
        },
        targetsAndAchieved: {
          annualTarget: "2.2L",
          achieved: "2L",
          quarterWise: [
            { quarter: "Q1", target: "55K", achieved: "45K" },
            { quarter: "Q2", target: "55K", achieved: "45K" },
            { quarter: "Q3", target: "55K", achieved: "45K" },
            { quarter: "Q4", target: "55K", achieved: "50K" },
          ],
        },
        headOfBrand: "Prashant Kumar",
      },
    ],
  },
];

export const subLocationsData = [
  { locationName: "Mumbai", subLocations: ["Andheri", "Bandra", "Colaba"] },
  { locationName: "Delhi", subLocations: ["Connaught Place", "Karol Bagh", "Lajpat Nagar"] },
  { locationName: "Bengaluru", subLocations: ["Koramangala", "Indiranagar", "MG Road"] },
  { locationName: "Kolkata", subLocations: ["Salt Lake", "Park Street", "New Town"] },
  { locationName: "Chennai", subLocations: ["T Nagar", "Adyar", "Velachery"] },
  { locationName: "Ahmedabad", subLocations: ["Maninagar", "Navrangpura", "Ghatlodia"] },
  { locationName: "Hyderabad", subLocations: ["Begumpet", "Banjara Hills", "Madhapur"] },
  { locationName: "Pune", subLocations: ["Koregaon Park", "Kothrud", "Viman Nagar"] },
  { locationName: "Surat", subLocations: ["Adajan", "Ghod Dod Road", "Ring Road"] },
  { locationName: "Jaipur", subLocations: ["C-Scheme", "Malviya Nagar", "Vaishali Nagar"] },
  { locationName: "Lucknow", subLocations: ["Hazratganj", "Gomti Nagar", "Indira Nagar"] },
  { locationName: "Kanpur", subLocations: ["Civil Lines", "Kalyanpur", "Swaroop Nagar"] },
  { locationName: "Nagpur", subLocations: ["Sitabuldi", "Civil Lines", "Ramdaspeth"] },
  { locationName: "Indore", subLocations: ["Rajwada", "Vijay Nagar", "Lal Baag"] },
  { locationName: "Thane", subLocations: ["Naupada", "Wagle Estate", "Ghodbunder Road"] },
  { locationName: "Bhopal", subLocations: ["MP Nagar", "Arera Colony", "Shahpura"] },
  { locationName: "Visakhapatnam", subLocations: ["Dwaraka Nagar", "MVP Colony", "Gajuwaka"] },
  { locationName: "Vadodara", subLocations: ["Alkapuri", "Sayajigunj", "Gotri"] },
  { locationName: "Ghaziabad", subLocations: ["Indirapuram", "Kaushambi", "Vaishali"] },
  { locationName: "Ludhiana", subLocations: ["Model Town", "Civil Lines", "Ferozepur Road"] },
  { locationName: "Agra", subLocations: ["Sadar Bazar", "Shahganj", "Trans Yamuna"] },
  { locationName: "Nashik", subLocations: ["Panchavati", "Satpur", "Indira Nagar"] },
  { locationName: "Faridabad", subLocations: ["Sector 15", "Sector 37", "Sector 21"] },
  { locationName: "Meerut", subLocations: ["Shastri Nagar", "Sadar Bazar", "Mawana Road"] },
  { locationName: "Rajkot", subLocations: ["Jubilee Garden", "Mavdi", "Kalavad Road"] },
  { locationName: "Kalyan-Dombivli", subLocations: ["Kalyan West", "Dombivli East", "Kalyan East"] },
  { locationName: "Vasai-Virar", subLocations: ["Vasai West", "Virar East", "Nallasopara"] },
  { locationName: "Varanasi", subLocations: ["Assi", "Sigra", "Bhelupur"] },
  { locationName: "Srinagar", subLocations: ["Rajbagh", "Shalteng", "Batamaloo"] },
  { locationName: "Aurangabad", subLocations: ["Cidco", "N-4", "Adalat Road"] },
  { locationName: "Dhanbad", subLocations: ["Jharia", "Sindri", "Katras"] },
  { locationName: "Amritsar", subLocations: ["Ranjit Avenue", "Green Avenue", "Majitha Road"] },
  { locationName: "Navi Mumbai", subLocations: ["Vashi", "Kharghar", "Belapur"] },
  { locationName: "Allahabad", subLocations: ["Civil Lines", "Kydganj", "Mau Aima"] },
  { locationName: "Ranchi", subLocations: ["Harmu", "Kanke", "Doranda"] },
  { locationName: "Chandigarh", subLocations: ["Sector 17", "Sector 22", "Sector 35"] },
  { locationName: "Coimbatore", subLocations: ["RS Puram", "Saibaba Colony", "Peelamedu"] },
  { locationName: "Mysuru", subLocations: ["Vijayanagar", "Jayalakshmipuram", "Nazarbad"] },
  { locationName: "Madurai", subLocations: ["Anna Nagar", "KK Nagar", "Tirupparankundram"] },
  { locationName: "Bhubaneswar", subLocations: ["Saheed Nagar", "Unit 9", "Kalinga Nagar"] },
  { locationName: "Jamshedpur", subLocations: ["Bistupur", "Golmuri", "Sonari"] },
  { locationName: "Dehradun", subLocations: ["Rajpur Road", "Mussoorie Road", "Haridwar Road"] },
  { locationName: "Aurangabad", subLocations: ["Cidco", "N-4", "Adalat Road"] },
  { locationName: "Kochi", subLocations: ["C-4", "Palak Pet", "Kochi Central"] },
];

export const indianFirstNames = [
  "Aarav", "Vivaan", "Aditya", "Kabir", "Arjun", 
  "Aryan", "Sai", "Ishaan", "Rohan", "Krishna",
  "Diya", "Ananya", "Aanya", "Aditi", "Ishita",
  "Meera", "Nandini", "Priya", "Saanvi", "Shreya",
  "Rahul", "Akshay", "Karan", "Vikram", "Manoj",
  "Rajesh", "Suresh", "Ravi", "Amit", "Pankaj",
  "Sneha", "Kavya", "Pooja", "Maya", "Neha",
  "Akhil", "Ritu", "Alok", "Gaurav", "Sunita",
  "Swati", "Vani", "Arpita", "Sakshi", "Harsha",
  "Pranav", "Nikhil", "Varun", "Kushal", "Parth"
];

export const indianLastNames = [
  "Sharma", "Gupta", "Mehta", "Verma", "Patel",
  "Reddy", "Nair", "Chowdhury", "Singh", "Yadav",
  "Rao", "Agarwal", "Joshi", "Chopra", "Das",
  "Ghosh", "Khan", "Pandey", "Kumar", "Iyer",
  "Nanda", "Thakur", "Pillai", "Shukla", "Bose",
  "Tiwari", "Chatterjee", "Roy", "Jain", "Dubey",
  "Malhotra", "Mishra", "Kapoor", "Bhat", "Naidu",
  "Venkatesh", "Murthy", "Dutta", "Deshmukh", "Banerjee",
  "Kulkarni", "Menon", "Sen", "Rastogi", "Ahluwalia",
  "Gill", "Sandhu", "Bajaj", "Bhattacharya", "Chhabra"
];

 
export const vehicleAccessories = [
  "Helmet with Bluetooth",
  "Alloy Wheels",
  "Car Seat Covers",
  "Dash Camera",
  "LED Headlights",
  "Floor Mats",
  "GPS Navigation System",
  "Bike Tank Bag",
  "Rearview Camera",
  "Mobile Phone Holder",
  "Roof Rack",
  "Bike Saddlebags",
  "Air Purifier",
  "Tow Hook",
  "Trunk Organizer",
  "Bike Handlebar Grips",
  "Parking Sensors",
  "Engine Guard",
  "Sunshade Visor",
  "Side Mirror Indicators"
];